### ISSUE TITLE
Fails to build... but still kinda works

### ISSUE THREAD

**Issue by DevinR528** [rust-linting/rust-linting#13]
When I run the command in the readme it builds and I get `dbg!` output but I also get
```
error: failed to run custom build command for `linter_api v0.1.0 (/home/devinr/aprog/rust/__forks__/rust-linting/linter_api)`

Caused by:
  could not execute process `/home/devinr/aprog/rust/__forks__/rust-linting/target/debug/build/linter_api-aa48e93580444ad5/build-script-build` (never executed)

Caused by:
  No such file or directory (os error 2)
warning: build failed, waiting for other jobs to finish...
```
I only noticed when I tried to only `dbg!` print the `ItemType::Function`.

**Comment by xFrednet** [comment]
Hmm, weird, on what crate do you try to run the linter?

**Comment by xFrednet** [comment]
For the `rust-linting` repo cargo might try to execute the `build.rs` file in `linter_api`. And it looks like this fails for some reason ...

**Comment by DevinR528** [comment]
Yeah I just did `cargo r --bin cargo-linter -- -l ./linter_lints` in the root of `rust-linting`

**Comment by DevinR528** [comment]
It seems like it fails because one of the commands expects the linter_api build.rs binary/executable file to be in `LINT_KRATES_OUT_DIR` but it's still in the normal `target/debug/build` instead of `target/linter/build/debug/build`

**Comment by xFrednet** [comment]
Hmm, that's weird. The script only sets the build version, that should be independent. Maybe `cargo_linter` sets an environment value that it shouldn't :thinking: Could you go a bit more into detail how you found this out. It didn't happen on my end, and therefore it's hard to fix :sweat_smile:

**Comment by DevinR528** [comment]
Yeah, these are the worst kinda bugs to track down! This only happens after the `Compiling Driver:`, `Compiling Lints` and 2 `Registering Lints` println's it then prints an extern item from (what I think) is the linter_api's build script or it could be indexmap/libc maybe. Then it fails saying that the build script for the linter_api wasn't found in `target/debug/build/linter-api-bighash/build-script-build`.

**Comment by xFrednet** [comment]
> May also be relevant: I removed all the prints in the lint except extern items and functions. (relevant in that there were many less prints so maybe easier to see the error)

That could be relevant. Do you have these changes on a branch? :upside_down_face:

**Comment by DevinR528** [comment]
Sorry I missed the notification for this. here it is https://github.com/rust-linting/rust-linting/pull/14

**Comment by xFrednet** [comment]
Okay, now I can see the error on master as well, I ignored it before, as it was somewhat working. My guess is that the following lines are the corporate:

https://github.com/rust-linting/rust-linting/blob/9bd9a37a1a5afcb563187f3725d0f30f29a8bab6/linter_driver_rustc/src/main.rs#L48-L54

This disables the generation on binary files. I thought we could do that, as there was no reason why we wanted to generate a binary, or so I've though... Without those lines everything works fine :partying_face:. It should be fine to remove them now, since the driver will be invoked by `cargo check` which avoids binary generation, unless it's required. I'll create a PR and assign it to you :)
